/** One audience and five concrete jobs, shared by onboarding and acceptance checks. */
export const BUSINESS_APPS = [
  { id: 'inventory', label: 'Inventory tool', detail: 'Know what is in stock and what needs ordering.', prompt: 'Build an inventory tool for a small business. Save products with SKU, quantity and reorder level in a database. Let me add products, adjust stock and see low-stock alerts. Require sign-in and keep each business’s records private.', fields: { sku: 'BH-100', quantity: 8, reorderLevel: 3 }, update: { quantity: 2 }, invalid: { quantity: -1 }, rule: 'Quantities and reorder levels must be non-negative integers; SKU must be unique per owner. Show a low-stock alert when quantity is at or below reorderLevel.' },
  { id: 'booking', label: 'Booking app', detail: 'Keep appointments clear and avoid double bookings.', prompt: 'Build a booking app for a small service business. Save customer appointments, start and end times, and status in a database. Prevent overlapping appointments, allow cancellation, and keep each signed-in business’s schedule private.', fields: { customer: 'Test customer', start: '2030-06-03T09:00:00Z', end: '2030-06-03T10:00:00Z', status: 'confirmed' }, update: { status: 'cancelled' }, invalid: { end: '2030-06-03T08:00:00Z' }, rule: 'Reject end times at or before start with HTTP 400. Prevent overlapping confirmed appointments for the same owner atomically with HTTP 409, including concurrent writes. Cancelling releases the slot.' },
  { id: 'crm', label: 'Simple CRM', detail: 'Keep customers and the next follow-up together.', prompt: 'Build a simple CRM for a small business. Save contacts, email addresses, notes and sales stages in a database. Let me add contacts and move leads through new, contacted and won. Keep customer data private to the signed-in business.', fields: { email: 'contact@example.invalid', stage: 'new', notes: 'Follow up Friday' }, update: { stage: 'won' }, invalid: { email: 'not-an-email' }, rule: 'Validate email addresses and allow only new, contacted or won stages. Filter contacts by stage. Keep notes private.' },
  { id: 'tasks', label: 'Task manager', detail: 'Turn the day’s work into a clear next step.', prompt: 'Build a task manager for a small business. Save tasks, due dates, priority and completion status in a database. Let me add tasks, mark them done and filter open tasks. Require sign-in and keep tasks private to their owner.', fields: { dueDate: '2030-06-03', priority: 'normal', status: 'open' }, update: { status: 'done' }, invalid: { priority: 'invalid' }, rule: 'Allow only low, normal and high priority and open or done status. Provide working open/completed filters.' },
  { id: 'portal', label: 'Customer portal', detail: 'Give each customer a private place for requests.', prompt: 'Build a customer portal for a small business. Customers sign in to create service requests, save details and track status. Store requests in a database and ensure customers can never read or change another customer’s requests.', fields: { message: 'Please update my delivery instructions.', status: 'open' }, update: { message: 'Please use the side entrance.' }, invalid: { message: '' }, rule: 'Require a non-empty message of at most 2000 characters. Customers can edit only their own requests and cannot impersonate an owner by submitting ownerId or userId.' },
] as const;

export function businessValidationPrompt(app: typeof BUSINESS_APPS[number], title: string) {
  return `${app.prompt}\nImplement this complete full-stack app now, titled ${JSON.stringify(title)}. Use the managed Workers backend, D1 and managed authentication already provided. Use a clean, accessible layout that works at 390px. Do not replace persistence with localStorage or an in-memory store.
For repeatable acceptance testing use this API contract: GET /api/records returns {records:[...]}; POST /api/records accepts {name,...fields} and returns {record:{id,name,...fields}} with HTTP 201; GET/PATCH/DELETE /api/records/:id returns {record} for reads/updates and {ok:true} for deletion. All routes require a real managed session (401 anonymous). Scope every read/write to the verified user; other users get 404 for a record ID and cannot see it in lists. Never trust caller-supplied owner fields. Reject invalid values with 400. ${app.rule}
The fields and a valid example are ${JSON.stringify(app.fields)}. A valid partial update is ${JSON.stringify(app.update)}. An invalid partial update is ${JSON.stringify(app.invalid)}.
For auditable persistence, use a D1 table named records with id, owner_id, name and payload columns; payload holds the JSON domain fields. Every saved record must exist there and owner_id must be the verified session user ID. Additional tables and indexes are allowed.
For the UI, provide an h1 exactly ${JSON.stringify(title)}, an input labelled Name, labelled inputs for each field (use the exact field keys as labels; plain input controls are fine), and a button Add record. Render saved records in a list labelled Records, with each record name visible. Include working edit/delete and the domain-specific behavior above. Show sign-in when needed through /__brainhalf/auth. UI writes must call these APIs.
Include migrations and real backend tests covering persistence, anonymous denial, another user’s GET/PATCH/DELETE denial, invalid input, and the business rule. Update brainhalf.verify.json for this app with API writes, direct D1 assertions, user isolation and browser checks. Keep the verification data disposable. Implement files and tests rather than only describing a plan.`;
}
