export async function exportToGitHub(
  files: Record<string, string>,
  repoName: string,
  token: string,
  owner?: string
) {
  const headers = {
    'Accept': 'application/vnd.github.v3+json',
    'Authorization': `Bearer ${token}`,
    'Content-Type': 'application/json',
  };

  const username = owner || await getAuthenticatedUser(headers);
  if (!username) throw new Error('Could not authenticate GitHub user.');

  // 1. Create or verify repo
  await ensureRepoExists(username, repoName, headers);

  // 2. Get latest commit SHA
  const refRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/refs/heads/main`, { headers });
  let baseTreeSha = '';
  let parentCommitSha = '';

  if (refRes.ok) {
    const refData = await refRes.json();
    parentCommitSha = refData.object.sha;
    const commitRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/commits/${parentCommitSha}`, { headers });
    const commitData = await commitRes.json();
    baseTreeSha = commitData.tree.sha;
  } else {
    // Repository is likely empty, we will create the initial commit without a base tree
    // Note: GitHub requires at least one commit to use the low-level Git Database API
    // We can auto-initialize with a README using the Contents API if empty.
    const initRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/contents/README.md`, {
      method: 'PUT',
      headers,
      body: JSON.stringify({
        message: 'Initial commit by BrainHalf AI',
        content: btoa('# ' + repoName + '\\n\\nGenerated by BrainHalf AI Studio.'),
      }),
    });
    if (!initRes.ok) throw new Error('Failed to initialize empty repository.');
    
    // Re-fetch refs
    const newRefRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/refs/heads/main`, { headers });
    if (!newRefRes.ok) throw new Error('Failed to get branch refs after initialization.');
    const refData = await newRefRes.json();
    parentCommitSha = refData.object.sha;
    
    const newCommitRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/commits/${parentCommitSha}`, { headers });
    const commitData = await newCommitRes.json();
    baseTreeSha = commitData.tree.sha;
  }

  // 3. Create tree
  const treeItems = [];
  for (const [filePath, content] of Object.entries(files)) {
    // Remove leading slash if any
    const cleanPath = filePath.startsWith('/') ? filePath.slice(1) : filePath;
    treeItems.push({
      path: cleanPath,
      mode: '100644',
      type: 'blob',
      content: content
    });
  }

  const treeRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/trees`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      base_tree: baseTreeSha,
      tree: treeItems
    }),
  });

  if (!treeRes.ok) {
    const err = await treeRes.json();
    throw new Error(`Failed to create git tree: ${err.message}`);
  }
  const treeData = await treeRes.json();
  const newTreeSha = treeData.sha;

  // 4. Create commit
  const commitPayload = {
    message: 'Update project files via BrainHalf AI Studio',
    tree: newTreeSha,
    parents: [parentCommitSha]
  };

  const commitRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/commits`, {
    method: 'POST',
    headers,
    body: JSON.stringify(commitPayload),
  });

  if (!commitRes.ok) {
    const err = await commitRes.json();
    throw new Error(`Failed to create commit: ${err.message}`);
  }
  const newCommitData = await commitRes.json();
  const newCommitSha = newCommitData.sha;

  // 5. Update reference
  const updateRefRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/refs/heads/main`, {
    method: 'PATCH',
    headers,
    body: JSON.stringify({
      sha: newCommitSha,
      force: true
    }),
  });

  if (!updateRefRes.ok) {
    const err = await updateRefRes.json();
    throw new Error(`Failed to update branch reference: ${err.message}`);
  }

  return `https://github.com/${username}/${repoName}`;
}

async function getAuthenticatedUser(headers: any) {
  const res = await fetch('https://api.github.com/user', { headers });
  if (!res.ok) return null;
  const data = await res.json();
  return data.login;
}

async function ensureRepoExists(username: string, repoName: string, headers: any) {
  const res = await fetch(`https://api.github.com/repos/${username}/${repoName}`, { headers });
  if (res.ok) return; // Exists

  // Create it
  const createRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: repoName,
      private: false,
      auto_init: false, // We handle initialization
      description: 'Project generated by BrainHalf AI Studio'
    })
  });

  if (!createRes.ok) {
    const err = await createRes.json();
    throw new Error(`Failed to create repository: ${err.message}`);
  }
}
