import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-expect-error — generated by `remix vite:build`
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
  build,
});
