const escape = (value: string) => value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]!));

/** A trusted auth page: email action tokens stay in the fragment and are consumed only after a user action. */
export function authPage(appName: string): Response {
  const nonce = crypto.randomUUID().replace(/-/g, '');
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in · ${escape(appName)}</title><style nonce="${nonce}">
  *{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f4f7fa;color:#142334;font:16px/1.5 system-ui,sans-serif;padding:24px}.card{width:100%;max-width:420px;background:#fff;border:1px solid #dbe3ea;border-radius:16px;padding:32px}h1{font-size:26px;line-height:1.2;margin:8px 0 24px}label{display:block;font-weight:600;margin:14px 0 6px}input,button,.google{width:100%;min-height:46px;border-radius:8px;font:inherit}input{padding:10px 12px;border:1px solid #94a3b8}button,.google{display:block;text-align:center;border:0;background:#176c85;color:#fff;padding:12px;cursor:pointer;font-weight:600;margin-top:20px;text-decoration:none}button:disabled{opacity:.6;cursor:wait}a{color:#176c85}.google{background:#fff;color:#142334;border:1px solid #94a3b8;margin:12px 0}.links{display:flex;gap:14px;flex-wrap:wrap;font-size:14px;margin-top:20px}.brand{font-size:13px;color:#526477}.message{white-space:pre-wrap;font-size:14px;margin-top:16px}input:focus-visible,button:focus-visible,a:focus-visible{outline:3px solid #74b8d0;outline-offset:3px}[hidden]{display:none!important}</style></head><body><main class="card"><p class="brand">${escape(appName)}</p><h1 id="title">Sign in</h1><a class="google" id="google" href="/api/auth/google/start" hidden>Continue with Google</a><form id="form" hidden><div id="name-field" hidden><label for="name">Name</label><input id="name" name="name" maxlength="100" autocomplete="name"></div><div id="email-field"><label for="email">Email</label><input id="email" name="email" type="email" maxlength="254" autocomplete="email" required></div><div id="password-field"><label for="password">Password</label><input id="password" name="password" type="password" minlength="8" maxlength="512" autocomplete="current-password" required></div><button id="submit" type="submit">Sign in</button></form><p class="message" id="message" role="status" aria-live="polite">Loading sign-in options…</p><nav class="links" id="auth-links" aria-label="Account options" hidden><a href="?mode=login">Sign in</a><a href="?mode=signup" id="signup-link">Create account</a><a href="?mode=forgot" id="forgot-link">Forgot password</a><a href="?mode=request-magic" id="magic-link">Email a sign-in link</a><a href="?mode=resend" id="resend-link">Resend verification</a></nav><p class="brand">Authentication provided by BrainHalf.</p></main><script nonce="${nonce}">
  const query=new URLSearchParams(location.search);const modes={login:['Sign in','Sign in','/api/auth/login'],signup:['Create account','Create account','/api/auth/signup'],forgot:['Reset password','Send reset link','/api/auth/forgot-password'],resend:['Verify your email','Send verification link','/api/auth/resend-verification'],verify:['Verify your email','Verify email','/api/auth/verify-email'],reset:['Choose a new password','Save password','/api/auth/reset-password'],magic:['Sign in with email','Confirm sign-in','/api/auth/magic-link/complete'],'request-magic':['Email sign-in link','Send sign-in link','/api/auth/magic-link']};const mode=modes[query.get('mode')]?query.get('mode'):'login';const action=modes[mode];let actionToken=new URLSearchParams(location.hash.slice(1)).get('token')||'';history.replaceState(null,'',location.pathname+location.search);const byId=id=>document.getElementById(id);byId('title').textContent=action[0];byId('submit').textContent=action[1];const usesEmail=['login','signup','forgot','resend','request-magic'].includes(mode);const usesPassword=['login','signup','reset'].includes(mode);byId('email-field').hidden=!usesEmail;byId('email').required=usesEmail;byId('password-field').hidden=!usesPassword;byId('password').required=usesPassword;byId('password').autocomplete=mode==='login'?'current-password':'new-password';byId('name-field').hidden=mode!=='signup';if(['verify','reset','magic'].includes(mode)&&!actionToken){byId('message').textContent='This link is missing its token. Request a new link.';byId('submit').disabled=true}if(query.has('error'))byId('message').textContent='Google sign-in did not finish. Please try again.';
  fetch('/api/auth/config').then(r=>{if(!r.ok)throw new Error('Sign-in unavailable');return r.json()}).then(c=>{if(byId('message').textContent==='Loading sign-in options…')byId('message').textContent='';byId('auth-links').hidden=false;byId('google').hidden=!c.googleReady||!['login','signup'].includes(mode);byId('signup-link').hidden=!c.passwordEnabled;byId('forgot-link').hidden=!c.passwordEnabled;byId('magic-link').hidden=!c.magicLinkEnabled||!c.emailReady;byId('resend-link').hidden=!c.emailReady;const unavailable=(['login','signup','forgot','reset'].includes(mode)&&!c.passwordEnabled)||(['request-magic','magic'].includes(mode)&&!c.magicLinkEnabled)||(['signup','forgot','resend','request-magic'].includes(mode)&&!c.emailReady);byId('form').hidden=unavailable;if(unavailable){byId('message').textContent=c.googleReady&&['login','signup'].includes(mode)?'Continue with Google to sign in.':'This sign-in method is unavailable. Choose another option or contact the app owner.'}if(c.development&&!byId('message').textContent)byId('message').textContent='Development: email links appear in the project test inbox.'}).catch(()=>{byId('message').textContent='Sign-in configuration could not load. Please reload this page.'});
  byId('form').addEventListener('submit',async event=>{event.preventDefault();const button=byId('submit');button.disabled=true;byId('message').textContent='Please wait…';try{const response=await fetch(action[2],{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:byId('email').value,password:byId('password').value,name:byId('name').value,token:actionToken})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');if(data.user){actionToken='';location.replace('/');return}byId('message').textContent=data.message||'Done. You can now sign in.';if(['verify','reset'].includes(mode)){actionToken='';byId('form').hidden=true}}catch(error){byId('message').textContent=error.message}finally{button.disabled=false}});
  </script></body></html>`;
  return new Response(html, { headers: {
    'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'Referrer-Policy': 'no-referrer', 'X-Content-Type-Options': 'nosniff', 'X-Robots-Tag': 'noindex, nofollow',
    'Content-Security-Policy': `default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'`,
  } });
}
