import { useEffect, useState, type FormEvent } from 'react';
interface Item { id:string; title:string; createdAt:number }
interface User { id:string; email:string }
async function api<T>(path:string, method='GET', body?:unknown):Promise<T> {
 const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 const data=await response.json(); if(!response.ok) throw new Error(data.error || 'Request failed'); return data as T;
}
export default function App(){
 const [user,setUser]=useState<User|null>(null),[items,setItems]=useState<Item[]>([]),[title,setTitle]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState<string|null>(null);
 useEffect(()=>{let active=true; void fetch('/api/auth/session').then(async r=>{if(r.status===401)return; const data=await r.json(); if(!r.ok)throw new Error(data.error || 'Could not load session'); if(data.user){const saved=await api<{items:Item[]}>('/api/items');if(active){setUser(data.user);setItems(saved.items);}}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 async function perform(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 function add(event:FormEvent){event.preventDefault();void perform(async()=>{const data=await api<{item:Item}>('/api/items','POST',{title});setItems(old=>[data.item,...old]);setTitle('');});}
 return <main className="app"><header><div><p className="eyebrow">BRAINHALF FULL-STACK EXAMPLE</p><h1>Brainhalf Task Board</h1></div>{user&&<button disabled={busy} onClick={()=>void perform(async()=>{await api('/api/auth/logout','POST',{});setUser(null);setItems([]);})}>Sign out</button>}</header><p>A private task list backed by a real database.</p>{error&&<p role="alert" className="error">{error}</p>}{loading?<p role="status">Loading your tasks…</p>:user?<><p>Signed in as {user.email}</p><form onSubmit={add}><label htmlFor="title">New task</label><div className="row"><input id="title" required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/><button disabled={busy||!title.trim()}>Add task</button></div></form><ul aria-label="Tasks">{items.map(item=><li key={item.id}><span>{item.title}</span>{deleting===item.id?<div className="row"><button disabled={busy} onClick={()=>void perform(async()=>{await api('/api/items/'+encodeURIComponent(item.id),'DELETE');setItems(old=>old.filter(i=>i.id!==item.id));setDeleting(null);})}>Confirm delete</button><button disabled={busy} onClick={()=>setDeleting(null)}>Cancel</button></div>:<button disabled={busy} aria-label={'Delete '+item.title} onClick={()=>setDeleting(item.id)}>Delete</button>}</li>)}</ul>{!items.length&&<p>No tasks yet. Add your first task above.</p>}</>:<a href="/__brainhalf/auth">Sign in to manage tasks</a>}{busy&&<p role="status">Saving changes…</p>}</main>;
}
