import { useEffect, useState } from 'react';
import { Activity } from 'lucide-react';
import { runtimeRequest } from '../lib/project-runtime-client';
import type { ProjectEnvironment } from '../runtime/types';

interface Monitoring { daily: Array<{ day: string; requests: number; errors: number; total_ms: number }>; recent: Array<{ method: string; route: string; status: number; duration_ms: number; created_at: number }> }
export default function ProjectMonitor({ projectId, environment }: { projectId: string; environment: ProjectEnvironment }) {
  const [data, setData] = useState<Monitoring | null>(null); const [error, setError] = useState(''); const [version, setVersion] = useState(0);
  useEffect(() => { const controller = new AbortController(); void runtimeRequest<Monitoring>(projectId, '/monitor', environment, { signal: controller.signal }).then(value => { setData(value); setError(''); }).catch(cause => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause.message : 'Monitoring unavailable.'); }); return () => controller.abort(); }, [projectId, environment, version]);
  const totals = data?.daily?.reduce((sum, day) => ({ requests: sum.requests + day.requests, errors: sum.errors + day.errors, duration: sum.duration + day.total_ms }), { requests: 0, errors: 0, duration: 0 });
  return <section className="settings-card"><h3><Activity size={17} />App monitoring</h3><p>Request activity for this environment. Seven days of totals and the most recent 100 requests; query strings, bodies and credentials are excluded.</p><button onClick={() => setVersion(value => value + 1)}>Refresh activity</button>{error && <p role="status">{error}</p>}{totals && <dl className="monitor-summary"><div><dt>Requests</dt><dd>{totals.requests.toLocaleString()}</dd></div><div><dt>Server errors</dt><dd>{totals.errors.toLocaleString()}</dd></div><div><dt>Average response</dt><dd>{totals.requests ? Math.round(totals.duration / totals.requests) : 0} ms</dd></div></dl>}{data && !data.recent?.length && <p>No hosted app requests yet. Open your development or production app to begin.</p>}{!!data?.recent?.length && <div className="settings-table-scroll" role="region" aria-label="Recent app requests" tabIndex={0}><table><thead><tr><th>Time</th><th>Request</th><th>Status</th><th>Duration</th></tr></thead><tbody>{data.recent.map((entry, index) => <tr key={index}><td>{new Date(entry.created_at).toLocaleTimeString()}</td><td>{entry.method} {entry.route}</td><td className={entry.status >= 500 ? 'settings-error' : ''}>{entry.status}</td><td>{entry.duration_ms} ms</td></tr>)}</tbody></table></div>}</section>;
}
