import type { PublicPage } from './content';

export const GROWTH_PAGES: PublicPage[] = [
  {
    path: '/use-cases/ai-inventory-app-builder',
    title: 'AI Inventory App Builder for Small Business | BrainHalf',
    description: 'Plan a custom inventory app with products, stock movements, low-stock alerts and staff permissions. Build with BrainHalf, test your records, then publish.',
    heading: 'Build an inventory app around your stock workflow',
    category: 'Inventory app builder', dateModified: '2026-09-24',
    summary: 'Use BrainHalf to build a custom inventory app by describing your products, stock changes and staff permissions. Ask for a managed database when records need to survive reloads and be shared by authorized users.',
    sections: [
      { id: 'choose-the-workflow', title: 'When does a custom inventory app make sense?', paragraphs: ['A small shop may need to record incoming deliveries, find low-stock products and explain why a quantity changed. A workshop may track materials consumed by jobs. Start with the workflow your spreadsheet makes awkward, rather than recreating every feature of a warehouse system.', 'An inventory app is a good first project when one location and a small catalog are enough. Barcode hardware, offline synchronization, accounting integrations and several warehouses add requirements that should be tested separately. This page provides a build brief and acceptance checklist; it is not a claim that every inventory feature is already built into BrainHalf.'] },
      { id: 'records', title: 'Define products and stock movements separately', paragraphs: ['Give each product a unique SKU, name, unit, opening quantity and reorder level. Record each later receipt, sale or adjustment as a stock movement with the product, quantity, reason, time and responsible user. Keeping the history helps explain the current balance.', 'For a first version, define current quantity as opening quantity plus receipts minus issues, with signed adjustments added. Use one unit per product: mixing boxes and individual pieces without a conversion rule produces misleading totals. Decide whether negative stock is permitted and what should happen when an SKU already exists.'], items: ['Product: SKU, name, unit, opening quantity and reorder level.', 'Movement: product, receipt or issue, quantity, reason and timestamp.', 'Permissions: owner manages staff and products; staff access only the actions you allow.', 'Low-stock view: products whose quantity is at or below the reorder level.'] },
      { id: 'inventory-prompt', title: 'Start with a specific inventory-app prompt', paragraphs: ['Replace the business type and permission rules with your own. Ask for a real database explicitly, and use synthetic records until the behavior has been checked.'], example: 'Build an inventory app for a small bicycle repair shop with one stockroom. Add products with a unique SKU, name, unit, opening quantity and reorder level. Let authorized staff record stock receipts and usage with a quantity and reason. Calculate balances from the movement history and show a searchable low-stock list. Require sign-in and keep each business account’s records private. Save records in a managed database so they survive reloads. Reject duplicate SKUs, empty names and negative movement quantities. Include mobile layouts and clear loading, empty and error states. Keep sample data clearly labeled.' },
      { id: 'stock-check', title: 'Test the stock calculation with numbers you know', paragraphs: ['Create a sample brake-pad product with an opening quantity of 10 pairs. Receive 5 pairs and issue 3. The balance should be 12 pairs, and the movement list should explain both changes. Set the reorder level to 12 and confirm the product appears in the low-stock list if your rule includes equality.', 'Submit the same action twice to see whether the app prevents duplicate stock changes. Try a blank SKU, an existing SKU, a negative quantity and a value with the wrong unit. Open the app in two sessions and check what happens when both people change the same product. A correct-looking dashboard is not enough.'], items: ['Reload and confirm the saved product and both movements remain.', 'Sign in with a separate business account and verify it cannot read the first account’s products.', 'Test a failed request: the form should preserve the input and avoid displaying an unsaved change as successful.', 'Use a phone to create a product and record a movement, including long names.', 'Compare summary totals, product details and exported records against the same small dataset.'] },
      { id: 'publish-inventory', title: 'Publish after the workflow passes', paragraphs: ['For supported managed apps, BrainHalf builds and verifies a saved version before activating the public release. Production has its own database; development test records are not copied. Test sign-in and a small disposable transaction on the public URL before adding real stock.', 'Keep the owner’s sign-in working and decide how to recover records before you depend on the app. Restoring source code does not restore a database. Source export is available, but hosted records and managed services need separate setup when you move to another provider.'], references: [{ label: 'Understand BrainHalf databases, sign-in and recovery', url: '/guides/full-stack-apps' }] },
    ],
    related: ['/guides/full-stack-apps', '/use-cases/ai-dashboard-builder', '/guides/build-an-app-with-ai'],
  },
  {
    path: '/guides/ai-appointment-app-example',
    title: 'Build an Appointment App with AI: Tested Example | BrainHalf',
    description: 'Follow a real BrainHalf build: the prompt, a design revision, form tests and a published appointment-request demo. See what worked and what still needs a backend.',
    heading: 'From a prompt to a published appointment-request demo',
    category: 'Tested app walkthrough', dateModified: '2026-09-24',
    summary: 'We used BrainHalf to generate, refine and publish Cedar Cuts, an appointment-request frontend for a fictional barber. Its form and mobile layout passed browser checks. It is a demonstration: it does not send requests, store bookings or reserve appointment slots.',
    sections: [
      { id: 'what-we-built', title: 'What the published example actually does', paragraphs: ['The app shows three services with prices, lets a visitor enter a name and preferred date, and displays a confirmation after validation. Its visible notice explains that requests are not sent or saved online. Cedar Cuts is a fictional example, and the service prices are demonstration data.', 'The screenshot below comes from the published app after a synthetic test submission. You can try the public demo with made-up information; a confirmation does not book a real appointment.'], references: [{ label: 'Try the Cedar Cuts frontend demo', url: 'https://deb260c733cb9b82876ea09cda516d76.apps.brainhalf.com' }], figure: { src: '/images/cedar-cuts-appointment-demo.webp', alt: 'Cedar Cuts mobile demo with three service choices, name and date fields, and a test confirmation', width: 390, height: 1024, caption: 'Published demo, tested on September 24, 2026. The name and appointment are synthetic; no booking is stored.' } },
      { id: 'initial-prompt', title: 'The initial prompt kept the scope small', paragraphs: ['We specified the business, fields, action and expected result. We also said that the first version should use local form state without a backend. This makes a frontend prototype easy to distinguish from a booking service that stores personal information.'], example: 'Create a small responsive appointment request frontend for a local barber called Cedar Cuts. Show three services and prices, a date input, a name input, and a Request appointment button. Validate both inputs and show a clear confirmation on submit. This is a frontend demo: say requests are not sent or saved online. Use React state, no backend, no external images or dependencies. Write the working app files now.' },
      { id: 'design-follow-up', title: 'The first version needed a design revision', paragraphs: ['The initial generation wrote the app and form components, but their styling was incomplete. We asked BrainHalf to finish the existing design with warm ivory, forest green, readable service cards, visible keyboard focus and a single-column mobile layout. We asked it to preserve the working form and frontend-only scope.', 'This follow-up mattered. The first successful generation event did not establish that the page looked finished. Open Preview, use the form and name the specific issue you want changed. If you are on a phone, switch from Chat to Preview before judging the layout.'] },
      { id: 'browser-checks', title: 'The checks we ran before and after publishing', paragraphs: ['We tested the saved app in the workspace, then repeated the main interactions on its public URL. The checks passed for this version; they do not cover every device or every possible input.'], items: ['Submitting an empty form shows messages for both the missing name and missing date.', 'Entering a test name and future date displays a confirmation containing that name.', 'The page fits a 390-pixel-wide viewport without horizontal overflow.', 'Reloading the workspace preserves the app source; reloading the public URL renders the app again.', 'The visible demo notice continues to explain that submissions are not saved or sent.'] },
      { id: 'observed-times', title: 'How long this build took', paragraphs: ['In this single September 24 test, the initial response appeared about 3.6 seconds after the browser sent the request. Generation finished in about 102 seconds. The separate styling request took about 89 seconds, and successful publication took about 80 seconds from the Publish click.', 'The run used BrainHalf’s default model and fast mode. These are individual observations, not typical latency, a load test or a promise for your project. Publication initially hit the account’s hosted-project limit; an unused reservation from an earlier failed installation was recovered before the successful attempt. Review and troubleshooting time are additional to the figures above.'] },
      { id: 'real-bookings', title: 'What would make this a real booking app?', paragraphs: ['A real booking workflow needs saved requests, a schedule, a rule for conflicting appointments and an owner who can review them. Decide whether a submission is only a request or an immediately confirmed reservation. Do not show “booked” until the server has accepted it.', 'Ask for a managed backend and database, then verify persistence and permissions. For email confirmations, verify the owner and configure sending before testing delivery to a controlled recipient. A working email configuration does not prove that a message reached an inbox.', 'Add these features incrementally. Test two people requesting the same time, cancellation, unavailable dates and failed network requests. The published Cedar Cuts demo has not implemented or passed those real-booking checks.'], references: [{ label: 'Build with a managed database, sign-in and email', url: '/guides/full-stack-apps' }] },
    ],
    related: ['/guides/build-an-app-with-ai', '/guides/full-stack-apps', '/use-cases/ai-website-builder'],
  },
];
